/**
 * Automated Report Generation for Experiment Results
 * 
 * Generates professional reports in multiple formats:
 * - HTML: Interactive web report with charts
 * - PDF: Printable report for stakeholders
 * - JSON: Machine-readable for downstream processing
 * - Markdown: For documentation/Slack sharing
 * 
 * Report sections:
 * - Executive Summary
 * - Experiment Configuration
 * - Statistical Results (primary/secondary metrics)
 * - Visualizations (effect size, confidence intervals)
 * - Recommendations
 * - Appendix (raw data, methodology)
 * 
 * @module lib/reports
 */

import { logger } from '@/lib/logger';
import type { ExperimentAnalysis, ExperimentMetric } from '@/lib/ab-testing';

export type ReportFormat = 'html' | 'pdf' | 'json' | 'markdown';

export interface ReportConfig {
  title: string;
  author: string;
  includeCharts: boolean;
  includeRawData: boolean;
  dateFormat: 'locale' | 'iso' | 'custom';
  customDatePattern?: string;
  
  // Branding
  logoUrl?: string;
  primaryColor?: string;
  footer?: string;
}

export interface ReportSection {
  id: string;
  title: string;
  content: string;
  order: number;
}

export class ReportGenerator {
  private config: ReportConfig;
  
  constructor(config: Partial<ReportConfig> = {}) {
    this.config = {
      title: 'Experiment Report',
      author: 'Citarion Infrastructure',
      includeCharts: true,
      includeRawData: false,
      dateFormat: 'locale',
      primaryColor: '#2563eb',
      footer: 'Generated by Citarion Algorithmic Trading Platform',
      ...config,
    };
  }

  /**
   * Generate report from experiment analysis
   */
  async generate(
    analysis: ExperimentAnalysis,
    format: ReportFormat = 'html',
    additionalData?: Record<string, any>
  ): Promise<string> {
    const sections = await this.buildSections(analysis, additionalData);
    
    switch (format) {
      case 'html':
        return this.generateHTML(sections, analysis);
      case 'pdf':
        // PDF generation would use a library like pdfkit or puppeteer
        // For now, return HTML that can be converted
        logger.warn('PDF format returns HTML - use external converter for PDF');
        return this.generateHTML(sections, analysis);
      case 'json':
        return this.generateJSON(sections, analysis);
      case 'markdown':
        return this.generateMarkdown(sections, analysis);
      default:
        throw new Error(`Unsupported format: ${format}`);
    }
  }

  /**
   * Build report sections from analysis
   */
  private async buildSections(
    analysis: ExperimentAnalysis,
    additionalData?: Record<string, any>
  ): Promise<ReportSection[]> {
    const sections: ReportSection[] = [];
    
    // 1. Executive Summary
    sections.push({
      id: 'summary',
      title: 'Executive Summary',
      content: await this.generateSummary(analysis),
      order: 1,
    });
    
    // 2. Experiment Configuration
    sections.push({
      id: 'config',
      title: 'Experiment Configuration',
      content: this.generateConfigSection(analysis),
      order: 2,
    });
    
    // 3. Statistical Results
    sections.push({
      id: 'results',
      title: 'Statistical Results',
      content: await this.generateResultsSection(analysis),
      order: 3,
    });
    
    // 4. Visualizations (if enabled)
    if (this.config.includeCharts) {
      sections.push({
        id: 'visualizations',
        title: 'Visualizations',
        content: this.generateChartsSection(analysis),
        order: 4,
      });
    }
    
    // 5. Recommendations
    sections.push({
      id: 'recommendations',
      title: 'Recommendations',
      content: this.generateRecommendationsSection(analysis),
      order: 5,
    });
    
    // 6. Appendix (if raw data enabled)
    if (this.config.includeRawData && additionalData) {
      sections.push({
        id: 'appendix',
        title: 'Appendix: Raw Data',
        content: this.generateAppendix(additionalData),
        order: 6,
      });
    }
    
    // Sort by order
    return sections.sort((a, b) => a.order - b.order);
  }

  /**
   * Generate executive summary
   */
  private async generateSummary(analysis: ExperimentAnalysis): Promise<string> {
    const primary = analysis.primaryResult;
    const status = analysis.status === 'CONCLUDED' ? 'Completed' : 
                   analysis.status === 'STOPPED_EARLY' ? 'Stopped Early' : 'Running';
    
    const recommendation = analysis.recommendations[0];
    
    return `
      <div class="summary-card">
        <h3>${analysis.experimentId}</h3>
        <div class="status-badge ${analysis.primaryResult.significant ? 'significant' : 'not-significant'}">
          ${primary.significant ? 'Statistically Significant' : 'Not Significant'}
        </div>
        <p><strong>Status:</strong> ${status}</p>
        <p><strong>Primary Metric:</strong> ${primary.metric}</p>
        <p><strong>Effect Size:</strong> ${(primary.effectSize * 100).toFixed(1)}%</p>
        <p><strong>P-value:</strong> ${primary.pValue.toFixed(4)}</p>
        <p><strong>95% CI:</strong> [${primary.confidenceInterval.lower.toFixed(4)}, ${primary.confidenceInterval.upper.toFixed(4)}]</p>
        <hr/>
        <p><strong>Recommendation:</strong> ${recommendation?.action || 'Pending analysis'}</p>
        <p><em>${recommendation?.rationale || ''}</em></p>
      </div>
    `;
  }

  /**
   * Generate configuration section
   */
  private generateConfigSection(analysis: ExperimentAnalysis): string {
    // Would pull from experiment config - simplified here
    return `
      <table class="config-table">
        <tr><td>Experiment ID</td><td>${analysis.experimentId}</td></tr>
        <tr><td>Analysis Date</td><td>${this.formatDate(analysis.analyzedAt)}</td></tr>
        <tr><td>Primary Metric</td><td>${analysis.primaryResult.metric}</td></tr>
        <tr><td>Significance Level</td><td>α = 0.05</td></tr>
        <tr><td>Statistical Power</td><td>1 - β = 0.80</td></tr>
        <tr><td>Test Type</td><td>Welch's t-test (unequal variance)</td></tr>
      </table>
    `;
  }

  /**
   * Generate results section
   */
  private async generateResultsSection(analysis: ExperimentAnalysis): Promise<string> {
    const primary = analysis.primaryResult;
    
    let html = `
      <h4>Primary Metric: ${primary.metric}</h4>
      <table class="results-table">
        <thead>
          <tr>
            <th>Group</th>
            <th>Sample Size</th>
            <th>Mean</th>
            <th>95% CI</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Control</td>
            <td>${primary.control.n}</td>
            <td>${primary.control.mean.toFixed(4)}</td>
            <td>-</td>
          </tr>
          <tr>
            <td>Treatment</td>
            <td>${primary.treatment.n}</td>
            <td>${primary.treatment.mean.toFixed(4)}</td>
            <td>[${primary.confidenceInterval.lower.toFixed(4)}, ${primary.confidenceInterval.upper.toFixed(4)}]</td>
          </tr>
        </tbody>
      </table>
      <p class="effect-size">
        <strong>Effect Size:</strong> ${(primary.effectSize * 100).toFixed(1)}% 
        ${primary.effectSize > 0 ? '↑ improvement' : '↓ degradation'}
      </p>
    `;
    
    // Secondary metrics
    if (analysis.secondaryResults.length > 0) {
      html += `
        <h4>Secondary Metrics</h4>
        <table class="results-table">
          <thead>
            <tr>
              <th>Metric</th>
              <th>Effect Size</th>
              <th>P-value</th>
              <th>Significant</th>
            </tr>
          </thead>
          <tbody>
      `;
      
      for (const sec of analysis.secondaryResults) {
        html += `
          <tr>
            <td>${sec.metric}</td>
            <td>${(sec.effectSize * 100).toFixed(1)}%</td>
            <td>${sec.pValue.toFixed(4)}</td>
            <td>${sec.significant ? '✅ Yes' : '❌ No'}</td>
          </tr>
        `;
      }
      
      html += `</tbody></table>`;
    }
    
    return html;
  }

  /**
   * Generate charts section (placeholder - would use charting library)
   */
  private generateChartsSection(analysis: ExperimentAnalysis): string {
    return `
      <div class="charts-placeholder">
        <p><em>Interactive charts would be rendered here using a library like Chart.js or D3.</em></p>
        <div class="chart-container">
          <h5>Effect Size with Confidence Interval</h5>
          <div class="chart-bar" style="width: ${Math.min(100, Math.max(0, 50 + analysis.primaryResult.effectSize * 100))}%"></div>
          <p class="chart-label">
            Control: ${analysis.primaryResult.control.mean.toFixed(2)} | 
            Treatment: ${analysis.primaryResult.treatment.mean.toFixed(2)}
          </p>
        </div>
      </div>
    `;
  }

  /**
   * Generate recommendations section
   */
  private generateRecommendationsSection(analysis: ExperimentAnalysis): string {
    if (analysis.recommendations.length === 0) {
      return '<p>No recommendations generated.</p>';
    }
    
    return `
      <ol class="recommendations">
        ${analysis.recommendations.map(rec => `
          <li>
            <strong>${rec.action}</strong> (${rec.confidence} confidence)<br/>
            <em>${rec.rationale}</em>
          </li>
        `).join('')}
      </ol>
    `;
  }

  /**
   * Generate appendix with raw data
   */
  private generateAppendix(data: Record<string, any>): string {
    return `
      <pre class="raw-data"><code>${JSON.stringify(data, null, 2).slice(0, 10000)}${JSON.stringify(data).length > 10000 ? '...' : ''}</code></pre>
      <p class="note"><em>Raw data truncated for display. Full data available in JSON export.</em></p>
    `;
  }

  /**
   * Generate full HTML report
   */
  private generateHTML(sections: ReportSection[], analysis: ExperimentAnalysis): string {
    const sectionsHtml = sections.map(s => `
      <section id="${s.id}">
        <h2>${s.title}</h2>
        ${s.content}
      </section>
    `).join('');
    
    return `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${this.config.title} - ${analysis.experimentId}</title>
        <style>
          :root { --primary: ${this.config.primaryColor}; }
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; max-width: 1200px; margin: 0 auto; padding: 2rem; color: #333; }
          h1 { color: var(--primary); border-bottom: 2px solid var(--primary); padding-bottom: 0.5rem; }
          h2 { color: #444; margin-top: 2rem; }
          .summary-card { background: #f8fafc; border-left: 4px solid var(--primary); padding: 1rem; margin: 1rem 0; border-radius: 0 4px 4px 0; }
          .status-badge { display: inline-block; padding: 0.25rem 0.75rem; border-radius: 9999px; font-size: 0.875rem; font-weight: 500; }
          .status-badge.significant { background: #dcfce7; color: #166534; }
          .status-badge.not-significant { background: #fef3c7; color: #92400e; }
          table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
          th, td { padding: 0.75rem; text-align: left; border-bottom: 1px solid #e5e7eb; }
          th { background: #f9fafb; font-weight: 600; }
          .effect-size { font-size: 1.1rem; margin: 1rem 0; }
          .recommendations { padding-left: 1.5rem; }
          .recommendations li { margin: 0.5rem 0; }
          .chart-container { background: #f3f4f6; padding: 1rem; border-radius: 8px; margin: 1rem 0; }
          .chart-bar { height: 2rem; background: var(--primary); border-radius: 4px; transition: width 0.3s; }
          .chart-label { font-size: 0.875rem; color: #6b7280; margin-top: 0.5rem; }
          .raw-data { background: #1e293b; color: #e2e8f0; padding: 1rem; border-radius: 4px; overflow-x: auto; font-family: monospace; font-size: 0.875rem; }
          .note { font-size: 0.875rem; color: #6b7280; font-style: italic; }
          footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 0.875rem; }
        </style>
      </head>
      <body>
        <header>
          <h1>${this.config.title}</h1>
          <p>Generated: ${this.formatDate(new Date())} | Author: ${this.config.author}</p>
          ${this.config.logoUrl ? `<img src="${this.config.logoUrl}" alt="Logo" style="max-height: 40px;"/>` : ''}
        </header>
        <main>
          ${sectionsHtml}
        </main>
        ${this.config.footer ? `<footer>${this.config.footer}</footer>` : ''}
      </body>
      </html>
    `;
  }

  /**
   * Generate JSON report
   */
  private generateJSON(sections: ReportSection[], analysis: ExperimentAnalysis): string {
    return JSON.stringify({
      metadata: {
        title: this.config.title,
        author: this.config.author,
        generatedAt: new Date().toISOString(),
        format: 'json',
      },
      experiment: {
        id: analysis.experimentId,
        status: analysis.status,
        analyzedAt: analysis.analyzedAt.toISOString(),
      },
      primaryResult: analysis.primaryResult,
      secondaryResults: analysis.secondaryResults,
      recommendations: analysis.recommendations,
      sections: sections.map(s => ({
        id: s.id,
        title: s.title,
        content: s.content,
      })),
    }, null, 2);
  }

  /**
   * Generate Markdown report
   */
  private generateMarkdown(sections: ReportSection[], analysis: ExperimentAnalysis): string {
    let md = `# ${this.config.title}\n\n`;
    md += `**Experiment:** ${analysis.experimentId}\n`;
    md += `**Generated:** ${this.formatDate(new Date())}\n`;
    md += `**Author:** ${this.config.author}\n\n`;
    md += `---\n\n`;
    
    for (const section of sections) {
      md += `## ${section.title}\n\n`;
      // Convert basic HTML to markdown (simplified)
      md += section.content
        .replace(/<h[3-5]>([^<]+)<\/h[3-5]>/g, '### $1\n')
        .replace(/<strong>([^<]+)<\/strong>/g, '**$1**')
        .replace(/<em>([^<]+)<\/em>/g, '*$1*')
        .replace(/<br\/?>/g, '\n')
        .replace(/<[^>]+>/g, '') // Remove remaining tags
        .trim();
      md += `\n\n---\n\n`;
    }
    
    return md.trim();
  }

  /**
   * Format date according to config
   */
  private formatDate(date: Date): string {
    switch (this.config.dateFormat) {
      case 'iso':
        return date.toISOString();
      case 'locale':
        return date.toLocaleString();
      case 'custom':
        // Would use a library like date-fns for custom patterns
        return date.toLocaleString();
      default:
        return date.toLocaleString();
    }
  }
}

// ==================== Singleton ====================

let _generator: ReportGenerator | null = null;

export function getReportGenerator(config?: Partial<ReportConfig>): ReportGenerator {
  if (!_generator) {
    _generator = new ReportGenerator(config);
  }
  return _generator;
}

// ==================== Convenience Function ====================

export async function generateExperimentReport(
  analysis: ExperimentAnalysis,
  format: ReportFormat = 'html',
  config?: Partial<ReportConfig>,
  additionalData?: Record<string, any>
): Promise<string> {
  const generator = getReportGenerator(config);
  return generator.generate(analysis, format, additionalData);
}

export default {
  ReportGenerator,
  getReportGenerator,
  generateExperimentReport,
  type ReportConfig,
  type ReportFormat,
  type ReportSection,
};
